/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IBondSDA, IBondSDAInterface } from "../IBondSDA";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes",
        name: "params_",
        type: "bytes",
      },
    ],
    name: "createMarket",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IBondSDA__factory {
  static readonly abi = _abi;
  static createInterface(): IBondSDAInterface {
    return new utils.Interface(_abi) as IBondSDAInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IBondSDA {
    return new Contract(address, _abi, signerOrProvider) as IBondSDA;
  }
}
