/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IBondTeller, IBondTellerInterface } from "../IBondTeller";

const _abi = [
  {
    inputs: [
      {
        internalType: "contract IERC20",
        name: "payoutToken",
        type: "address",
      },
      {
        internalType: "uint48",
        name: "expiration",
        type: "uint48",
      },
      {
        internalType: "uint256",
        name: "capacity",
        type: "uint256",
      },
    ],
    name: "create",
    outputs: [
      {
        internalType: "contract IERC20",
        name: "",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "contract IERC20",
        name: "payoutToken",
        type: "address",
      },
      {
        internalType: "uint48",
        name: "expiration",
        type: "uint48",
      },
    ],
    name: "deploy",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IBondTeller__factory {
  static readonly abi = _abi;
  static createInterface(): IBondTellerInterface {
    return new utils.Interface(_abi) as IBondTellerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IBondTeller {
    return new Contract(address, _abi, signerOrProvider) as IBondTeller;
  }
}
