/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  OlympusAccessControlledV2,
  OlympusAccessControlledV2Interface,
} from "../OlympusAccessControlledV2";

const _abi = [
  {
    inputs: [],
    name: "UNAUTHORIZED",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "contract IOlympusAuthority",
        name: "authority",
        type: "address",
      },
    ],
    name: "AuthorityUpdated",
    type: "event",
  },
  {
    inputs: [],
    name: "authority",
    outputs: [
      {
        internalType: "contract IOlympusAuthority",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "contract IOlympusAuthority",
        name: "_newAuthority",
        type: "address",
      },
    ],
    name: "setAuthority",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class OlympusAccessControlledV2__factory {
  static readonly abi = _abi;
  static createInterface(): OlympusAccessControlledV2Interface {
    return new utils.Interface(_abi) as OlympusAccessControlledV2Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): OlympusAccessControlledV2 {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as OlympusAccessControlledV2;
  }
}
