import Navbar from "@/components/Navbar";
import { Anonymous_Pro } from "next/font/google";
import "./globals.css";

const inter = Anonymous_Pro({ weight: ["400", "700"], subsets: ["latin"] });

export const metadata = {
  title: "juice",
  description: "Generated by juice",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <div className="px-6 mb-20">{children}</div> 
      </body>
    </html>
  );
}
